// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Handshake protocol data used for both request and response - sent unencrypted over the wire
type HandshakeData struct {
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	NetworkID            int32    `protobuf:"varint,2,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeData) Reset()         { *m = HandshakeData{} }
func (m *HandshakeData) String() string { return proto.CompactTextString(m) }
func (*HandshakeData) ProtoMessage()    {}
func (*HandshakeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_5c87de8978a28cc9, []int{0}
}
func (m *HandshakeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeData.Unmarshal(m, b)
}
func (m *HandshakeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeData.Marshal(b, m, deterministic)
}
func (dst *HandshakeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeData.Merge(dst, src)
}
func (m *HandshakeData) XXX_Size() int {
	return xxx_messageInfo_HandshakeData.Size(m)
}
func (m *HandshakeData) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeData.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeData proto.InternalMessageInfo

func (m *HandshakeData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *HandshakeData) GetNetworkID() int32 {
	if m != nil {
		return m.NetworkID
	}
	return 0
}

func (m *HandshakeData) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// used for protocol messages (non-handshake) - this is the decrypted CommonMessageData.payload
// it allows multiplexing back to higher level protocols
// data is here and not in CommonMessageData to avoid leaked data on unencrypted connections
type ProtocolMessage struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ProtocolMessage_Payload
	//	*ProtocolMessage_Msg
	Data                 isProtocolMessage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProtocolMessage) Reset()         { *m = ProtocolMessage{} }
func (m *ProtocolMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage) ProtoMessage()    {}
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_5c87de8978a28cc9, []int{1}
}
func (m *ProtocolMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolMessage.Unmarshal(m, b)
}
func (m *ProtocolMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolMessage.Marshal(b, m, deterministic)
}
func (dst *ProtocolMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolMessage.Merge(dst, src)
}
func (m *ProtocolMessage) XXX_Size() int {
	return xxx_messageInfo_ProtocolMessage.Size(m)
}
func (m *ProtocolMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolMessage proto.InternalMessageInfo

func (m *ProtocolMessage) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type isProtocolMessage_Data interface {
	isProtocolMessage_Data()
}

type ProtocolMessage_Payload struct {
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

type ProtocolMessage_Msg struct {
	Msg *MessageWrapper `protobuf:"bytes,3,opt,name=msg,proto3,oneof"`
}

func (*ProtocolMessage_Payload) isProtocolMessage_Data() {}

func (*ProtocolMessage_Msg) isProtocolMessage_Data() {}

func (m *ProtocolMessage) GetData() isProtocolMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ProtocolMessage) GetPayload() []byte {
	if x, ok := m.GetData().(*ProtocolMessage_Payload); ok {
		return x.Payload
	}
	return nil
}

func (m *ProtocolMessage) GetMsg() *MessageWrapper {
	if x, ok := m.GetData().(*ProtocolMessage_Msg); ok {
		return x.Msg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ProtocolMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ProtocolMessage_OneofMarshaler, _ProtocolMessage_OneofUnmarshaler, _ProtocolMessage_OneofSizer, []interface{}{
		(*ProtocolMessage_Payload)(nil),
		(*ProtocolMessage_Msg)(nil),
	}
}

func _ProtocolMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ProtocolMessage)
	// data
	switch x := m.Data.(type) {
	case *ProtocolMessage_Payload:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Payload)
	case *ProtocolMessage_Msg:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ProtocolMessage.Data has unexpected type %T", x)
	}
	return nil
}

func _ProtocolMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ProtocolMessage)
	switch tag {
	case 2: // data.payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Data = &ProtocolMessage_Payload{x}
		return true, err
	case 3: // data.msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MessageWrapper)
		err := b.DecodeMessage(msg)
		m.Data = &ProtocolMessage_Msg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ProtocolMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ProtocolMessage)
	// data
	switch x := m.Data.(type) {
	case *ProtocolMessage_Payload:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Payload)))
		n += len(x.Payload)
	case *ProtocolMessage_Msg:
		s := proto.Size(x.Msg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Metadata struct {
	NextProtocol         string   `protobuf:"bytes,1,opt,name=nextProtocol,proto3" json:"nextProtocol,omitempty"`
	ClientVersion        string   `protobuf:"bytes,2,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AuthPubkey           []byte   `protobuf:"bytes,4,opt,name=authPubkey,proto3" json:"authPubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_5c87de8978a28cc9, []int{2}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetNextProtocol() string {
	if m != nil {
		return m.NextProtocol
	}
	return ""
}

func (m *Metadata) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *Metadata) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Metadata) GetAuthPubkey() []byte {
	if m != nil {
		return m.AuthPubkey
	}
	return nil
}

type MessageWrapper struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Req                  bool     `protobuf:"varint,2,opt,name=req,proto3" json:"req,omitempty"`
	ReqID                uint64   `protobuf:"varint,3,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWrapper) Reset()         { *m = MessageWrapper{} }
func (m *MessageWrapper) String() string { return proto.CompactTextString(m) }
func (*MessageWrapper) ProtoMessage()    {}
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_5c87de8978a28cc9, []int{3}
}
func (m *MessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWrapper.Unmarshal(m, b)
}
func (m *MessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWrapper.Marshal(b, m, deterministic)
}
func (dst *MessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWrapper.Merge(dst, src)
}
func (m *MessageWrapper) XXX_Size() int {
	return xxx_messageInfo_MessageWrapper.Size(m)
}
func (m *MessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWrapper proto.InternalMessageInfo

func (m *MessageWrapper) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageWrapper) GetReq() bool {
	if m != nil {
		return m.Req
	}
	return false
}

func (m *MessageWrapper) GetReqID() uint64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *MessageWrapper) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*HandshakeData)(nil), "pb.HandshakeData")
	proto.RegisterType((*ProtocolMessage)(nil), "pb.ProtocolMessage")
	proto.RegisterType((*Metadata)(nil), "pb.Metadata")
	proto.RegisterType((*MessageWrapper)(nil), "pb.MessageWrapper")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_5c87de8978a28cc9) }

var fileDescriptor_message_5c87de8978a28cc9 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0xe9, 0x1f, 0x10, 0x06, 0xaa, 0x66, 0xe2, 0xa1, 0x31, 0xc6, 0x90, 0xc6, 0x98, 0x9e,
	0x38, 0xe0, 0x1b, 0x10, 0x0e, 0x70, 0x20, 0x21, 0x7b, 0xd0, 0xc4, 0xdb, 0x14, 0x46, 0x20, 0xd0,
	0xee, 0xb2, 0x5d, 0xa2, 0x3c, 0x81, 0x77, 0x9f, 0xd8, 0x74, 0x4b, 0xc5, 0xc6, 0x78, 0x9b, 0xfd,
	0xb5, 0x99, 0xdf, 0xb7, 0x5f, 0x16, 0x82, 0x94, 0xf3, 0x9c, 0x56, 0x3c, 0x50, 0x5a, 0x1a, 0x89,
	0xae, 0x4a, 0xa2, 0x15, 0x04, 0x13, 0xca, 0x96, 0xf9, 0x9a, 0xb6, 0x3c, 0x26, 0x43, 0xf8, 0x00,
	0xc1, 0x62, 0xb7, 0xe1, 0xcc, 0x3c, 0xb3, 0xce, 0x37, 0x32, 0x0b, 0x9d, 0xbe, 0x13, 0x77, 0x44,
	0x1d, 0xe2, 0x1d, 0x74, 0x32, 0x36, 0xef, 0x52, 0x6f, 0xa7, 0xe3, 0xd0, 0xed, 0x3b, 0x71, 0x53,
	0x9c, 0x01, 0x22, 0xf8, 0x4a, 0x6a, 0x13, 0x7a, 0x7d, 0x27, 0x0e, 0x84, 0x9d, 0xa3, 0x4f, 0x07,
	0xae, 0xe6, 0x85, 0x76, 0x21, 0x77, 0xb3, 0x32, 0x06, 0xc6, 0xd0, 0x4e, 0xd9, 0xd0, 0x92, 0x0c,
	0x59, 0x4d, 0x77, 0xd8, 0x1b, 0xa8, 0x64, 0x30, 0x3b, 0x31, 0xf1, 0xf3, 0x15, 0x6f, 0xe1, 0x42,
	0xd1, 0x71, 0x27, 0x69, 0x69, 0x6d, 0xbd, 0x49, 0x43, 0x54, 0x00, 0x1f, 0xc1, 0x4b, 0xf3, 0x95,
	0x95, 0x75, 0x87, 0x58, 0x2e, 0xb0, 0xfb, 0x5f, 0x34, 0x29, 0xc5, 0x7a, 0xd2, 0x10, 0xc5, 0x0f,
	0xa3, 0x16, 0xf8, 0xc5, 0xae, 0xe8, 0xcb, 0x81, 0x76, 0xa5, 0xc0, 0x08, 0x7a, 0x19, 0x7f, 0x98,
	0x2a, 0xd9, 0xe9, 0xb6, 0x35, 0xf6, 0xb7, 0x12, 0xf7, 0x9f, 0x4a, 0xcc, 0x26, 0xe5, 0xdc, 0x50,
	0xaa, 0x6c, 0x18, 0x4f, 0x9c, 0x01, 0xde, 0x03, 0xd0, 0xc1, 0xac, 0xe7, 0x87, 0x64, 0xcb, 0xc7,
	0xd0, 0x2f, 0xee, 0x20, 0x7e, 0x91, 0xe8, 0x0d, 0x2e, 0xeb, 0xa9, 0x8b, 0x12, 0xcd, 0x51, 0xb1,
	0x4d, 0x14, 0x08, 0x3b, 0xe3, 0x35, 0x78, 0x9a, 0xf7, 0xd6, 0xdf, 0x16, 0xc5, 0x88, 0x37, 0xd0,
	0xd4, 0xbc, 0x9f, 0x8e, 0xad, 0xd1, 0x17, 0xe5, 0x01, 0xc3, 0x73, 0x5d, 0xa5, 0xaa, 0x3a, 0x8e,
	0xfc, 0x57, 0x57, 0x25, 0x49, 0xcb, 0x3e, 0x80, 0xa7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0x41, 0xd3, 0xda, 0x11, 0x02, 0x00, 0x00,
}
